### ISSUE TITLE
[CHORE] Assignment 1 - ToDo

### ISSUE THREAD

**Issue by pandamarty** [pandamarty/mobile-systems-eng#1]
The aim of this assignment is to create a rip-off of the game Wordle.
Here are the steps we need to take to reach the goal.

### TO-DO
- [ ] Create 5 columns x 6 rows table in console for words input
- [ ] Create 10 columns x 3 rows table for digital keyboard record
- [ ] Create "Your guess?" input at the bottom
- [ ] Connect input with rows in table
  - [ ] Divide word for each spot
- [ ] Save used keys with color codes in digital keyboard
  - [ ] Compare to not used letters
  - [ ] Check if letter is in reference word

Word check:
- [ ] Loop through letters in word
- [ ] If letter in word -> check if index is the same

**Comment by pandamarty** [comment]
### COMMANDS
If the word has 4 letters, then it's a command.
- [ ] QUIT: exit the game
- [ ] HELP: print the list of commands and their description
- [ ] HARD: restart a game, in hard mode
- [ ] EASY: restart a game, in normal mode
- [ ] STAT: print some statistics
  - [ ] After each game -> saves number of rows used
  - [ ] These stats are printed out with this command
  - [ ] Everything is erased after QUIT is used
- [ ] Any number: restarts the game, but using the number as index to get a word in the list (useful for testing)
