### ISSUE TITLE
[FIX] Professor's feedback

### ISSUE THREAD

**Issue by pandamarty** [pandamarty/mobile-systems-eng#3]
### 1.
- [x] rewrite code in Typescript
### 2.
- [x] optimize app for landscape mode
### 3.
- [x] check word lists to validate entries
### 4.
- [x] fix algorithm to match letters, which does not handle multiple letters (meaning, when the correct word only contains one 'E' for example, the app colors in yellow also 2 'E's, if in input)
### 5.
- [x] finish implementing QR code scanning
### 6.
- [x] finish implementing dictionary API 
#### 6.5
  - [x] implement new random word if you play several times
### 7.
  - [x] implement hard mode
### 8
- [x] fix end screen statistics

**Comment by pandamarty** [comment]
### To fix the algorithms to count letters
- create two objects with tuples `{ "letterOfAlphabet" : count }`, `rightWordCheck` and `inputCheck`
- at the beginning of the game, where the word to guess is sorted, loop through the word and increment each count for property `"letterOfAlphabet" == currentLetter` in `rightWordCheck`
- while looping through the input word, instead, increment each count for property `"letterOfAlphabet" == currentLetter` in `inputCheck`
- for coloring the letters, we do a check, where if the count for a given letter is the same in both lists, then they're colored based on the other rules; if they're different, then the absolute value of `rightWordCheck - inputCheck` has to be colored grey according to the other rules as well

- [ ] review

**Comment by pandamarty** [comment]
## 1 - rewrite code in TS
### References
- **https://github.com/gregjacobs/js-to-ts-converter**
- https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html
- https://www.youtube.com/watch?v=XqC1m2zJc4Y&ab_channel=NeverAll
- https://www.youtube.com/watch?v=OdU9H-_d14Y&ab_channel=CodingTech
- https://www.bam.tech/article/how-to-migrate-an-existing-react-native-project-from-javascript-to-typescript
### Task analysis
- Writing a configuration file
- Integrating build tools -> Webpack
- Change `.js` file extensions to `.ts`
- Correct syntax errors to "translate" code into TypeScript
  - to not allow TS to compile JS if there are syntax errors: `noEmitOnError`
- Convert imports into TS syntax
  - https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html#weeding-out-errors

**Comment by pandamarty** [comment]
## 5 - finish implementing QR code scanning
- [x] create 'game' object by embedding chosen word
- [x] turn object into QR Code
- [x] by scanning QR Code, get 'game' object
- [x] start game and set guess word to chosen word

**Comment by pandamarty** [comment]
## 8 - fix end screen statistics
- [x] show guess distribution line
- [x] fix streaks
- [x] reset game object

**Comment by pandamarty** [comment]
## 2 - optimize app for landscape mode
- or don't support landscape mode?
- `ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT);`
